consul:
    hostname: consul
    image: qnib/consul
    environment:
     - DC_NAME=dc1
     - BOOTSTRAP_CONSUL=true
     - RUN_SERVER=true 
    ports:
    - "8500:8500"
    dns: 127.0.0.1

zkui:
    hostname: zkui
    dns: 127.0.0.1
    image: qnib/zkui
    environment:
    - DC_NAME=dc1
    links:
    - consul:consul
    ports:
    - 9090:9090
    privileged: true

zookeeper0:
    hostname: zookeeper0
    dns: 127.0.0.1
    image: qnib/zookeeper
    #volumes:
    #- opt/qnib/zookeeper/bin/:/opt/qnib/zookeeper/bin/
    environment:
    - DC_NAME=dc1
    - MYID=1
    #- START_ZOOKEEPER=false
    - SERVERS=zookeeper0.node.dc1.consul,zookeeper1.node.dc1.consul,zookeeper2.node.dc1.consul
    links:
    - consul:consul
    ports:
    - 2181:2181
    privileged: true

zookeeper1:
    hostname: zookeeper1
    dns: 127.0.0.1
    image: qnib/zookeeper
    environment:
    - DC_NAME=dc1
    - MYID=2
    - SERVERS=zookeeper0.node.dc1.consul,zookeeper1.node.dc1.consul,zookeeper2.node.dc1.consul
    links:
    - consul:consul
    privileged: true

zookeeper2:
    hostname: zookeeper2
    dns: 127.0.0.1
    image: qnib/zookeeper
    environment:
    - DC_NAME=dc1
    - MYID=3
    - SERVERS=zookeeper0.node.dc1.consul,zookeeper1.node.dc1.consul,zookeeper2.node.dc1.consul
    links:
    - consul:consul
    privileged: true
